apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-guestbook-frontend
  namespace: default
spec:
  replicas: 6
  selector:
    matchLabels:
        app: py-guestbook
        tier: frontend
        version: v5
  template:
    metadata:
      labels:
        app: py-guestbook
        tier: frontend
        version: v5
    spec:
      containers:
      - name: py-redis
        image: docker.io/ansustiwaz/redis-py:v5
        env:
        - name: REDIS_HOST
          value: "redis-leader"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 5000
