apiVersion: v1
kind: Service
metadata:
  name: py-guestbook-frontend
  namespace: default
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: py-guestbook
    tier: frontend
  type: ClusterIP
