apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- redis-leader-deployment.yaml
- redis-leader-service.yaml
- redis-follower-deployment.yaml
- redis-follower-service.yaml
- frontend-deployment-python.yaml
- frontend-service-python.yaml
- namespace.yaml
