---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
    name: eks-2023
    region: eu-central-1

nodeGroups:
    - name: eks-2023-ng-private1
      minSize: 2
      maxSize: 5
      instancesDistribution:
        maxPrice: 0.017
        instanceTypes: ["t3.small", "t3.medium"]
        onDemandBaseCapacity: 0
        onDemandPercentageAboveBaseCapacity: 25
        spotInstancePools: 2
      privateNetworking: true
