apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: demo-cert
spec:
  commonName: demo.rusty.systems
  secretName: demo-cert
  dnsNames:
    - demo.rusty.systems
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
