apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-statefull
spec:
  acme:
    email: ansustiwaz@gmail.com
    privateKeySecretRef:
      name: letsencrypt-statefull
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx
          serviceType: ClusterIP
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wp-cert
  namespace: statefull
spec:
  commonName: wp.rusty.systems
  dnsNames:
  - wp.rusty.systems
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-statefull
  secretName: wp-cert
